import { Outfit } from "next/font/google";  
import "./globals.css";
import Navbar from "@/components/Landingpage/Navbar";
import Footer from "@/components/Landingpage/Footer";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], // add/remove weights as needed
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>

        <link href="https://cdn.jsdelivr.net/npm/daisyui@5" rel="stylesheet" type="text/css" />
      </head>
      <body className={`${outfit.variable} antialiased`}>
        <main>
          <Navbar />
          {children}
          <Footer />


        </main>

        
<script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"/>
      </body>
    </html>
  );
}
